--
-- PostgreSQL database dump
--

\restrict MkmNB3bwmuuDP4NX3iIXelNHh3MKbYIJwTgTHWkXzPGxbbIX9BzqjvVrKxLO45T

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: Availability; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public."Availability" AS ENUM (
    'available',
    'not_available'
);


ALTER TYPE public."Availability" OWNER TO postgres;

--
-- Name: Status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public."Status" AS ENUM (
    'active',
    'inactive'
);


ALTER TYPE public."Status" OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: branches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.branches (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.branches OWNER TO postgres;

--
-- Name: branches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.branches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_branch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_branch (
    id integer NOT NULL,
    product_id integer NOT NULL,
    stock integer NOT NULL,
    price numeric(10,2) NOT NULL,
    branch_id integer NOT NULL,
    branch_status public."Status" DEFAULT 'active'::public."Status" NOT NULL,
    availability public."Availability" DEFAULT 'available'::public."Availability" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT chk_no_negative_stocks CHECK ((stock >= 0))
);


ALTER TABLE public.product_branch OWNER TO postgres;

--
-- Name: product_branch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_branch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_branch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    category_id integer,
    threshold integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: branches branches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT branches_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: product_branch product_branch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_branch
    ADD CONSTRAINT product_branch_pkey PRIMARY KEY (id);


--
-- Name: products products_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_name_key UNIQUE (name);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: branch_product; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX branch_product ON public.product_branch USING btree (branch_id, product_id);


--
-- Name: branches_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX branches_id_idx ON public.branches USING btree (id);


--
-- Name: branches_name_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX branches_name_idx ON public.branches USING btree (name);


--
-- Name: categories_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX categories_id_idx ON public.categories USING btree (id);


--
-- Name: categories_name_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX categories_name_idx ON public.categories USING btree (name);


--
-- Name: product_branch_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX product_branch_id_idx ON public.product_branch USING btree (id);


--
-- Name: products_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX products_id_idx ON public.products USING btree (id);


--
-- Name: products_name_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX products_name_idx ON public.products USING btree (name);


--
-- Name: product_branch product_branch_branch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_branch
    ADD CONSTRAINT product_branch_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) DEFERRABLE;


--
-- Name: product_branch product_branch_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_branch
    ADD CONSTRAINT product_branch_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE DEFERRABLE;


--
-- Name: products products_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE;


--
-- PostgreSQL database dump complete
--

\unrestrict MkmNB3bwmuuDP4NX3iIXelNHh3MKbYIJwTgTHWkXzPGxbbIX9BzqjvVrKxLO45T

